# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20151222_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='style',
            new_name='estilo',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='linguagem',
        ),
    ]
